version: "3.8"

services:
  portainer:
    image: portainer/portainer-ce:2.20.2-alpine
    container_name: portainer
    restart: unless-stopped
    ports:
      - "7779:9000"
      - "7443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./portainer_data:/data:rw

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: $PWD/portainer_data
      o: bind